smallthinker_cached_slim_src = [
    meson.current_source_dir() / 'smallthinker_cached_slim_causallm.cpp',
    meson.current_source_dir() / 'smallthinker_moe_layer_cached_slim.cpp',
]

smallthinker_cached_slim_inc = include_directories('.')

quick_dot_ai_src += smallthinker_cached_slim_src
quick_dot_ai_inc += smallthinker_cached_slim_inc
